replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "stable-alpine"

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 80


livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http


nodeSelector: {}

tolerations: []

affinity: {}
