apiVersion: v1
kind: Service
metadata:
  name: {{ include "wallet-service-mesh-helm.fullname" . }}
  labels:
    {{- include "wallet-service-mesh-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 80  }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "wallet-service-mesh-helm.selectorLabels" . | nindent 4 }}