apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-poc
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - environment: test
            server: https://kubernetes.default.svc
      - list:
          elements:
          - name: 1
            repoPath: helm-chart
            namespace: wallet
          - name: 2
            repoPath: helm-chart
            namespace: wallet

  template:
    metadata:
      name: "{{name}}-{{environment}}"
    spec:
      project: argocd-poc
      source:
        repoURL: https://github.com/m-alabi/argocd-poc.git
        path: "{{repoPath}}"
        targetRevision: HEAD
        helm:
          valueFiles:
          - "values-{{name}}.yaml"
      destination:
        server: "{{server}}"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - ServerSideApply=true
